site_name: Kai's statistics & engineering lab

theme:
    name: material
    # Use Highlight.js library for syntax highlighting for code blocks
    highlightjs: true

nav:
    - Home: index.md
    - Rust projects:
          - Introduction: rust_projects/introduction.md
          - Linear regression: rust_projects/linear_regression.md

markdown_extensions:
    - attr_list
    # Enable highlighted note/important blocks
    - admonition
    - pymdownx.arithmatex: # for rendering LaTeX math
          generic: true
    # For enabling checkboxes in task lists
    - pymdownx.tasklist:
          custom_checkbox: true

extra_javascript: # for rendering LaTeX math
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
