name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_rust_linear_regression:
    name: Test Rust Linear Regression Project
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    defaults:
      run:
        working-directory: ./rust_projects/linear_regression

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt, llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          # this action does not use default.run because it is a "uses" step
          workspaces: "rust_projects/linear_regression -> target"

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests with coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v5
        with:
          coverage-files: rust_projects/linear_regression/lcov.info
          minimum-coverage: 80
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true

  build_and_smoke_test_docker_image:
    name: Build and Smoke Test Docker Image for Rust Linear Regression Project
    needs: test_rust_linear_regression
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./rust_projects/linear_regression

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and smoke test Docker image
        run: |
          version=$(grep -m1 '^version =' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          docker build -t linear_regression:"$version" -f docker/Dockerfile .
          output=$(docker run --rm linear_regression:"$version" 2>&1)
          echo "$output"
          # if [[ "$output" == *"Usage: linear_regression <input_file> <output_file>"* ]]; then
          #   echo "Smoke test passed."
          # else
          #   echo "Smoke test failed."
          #   exit 1
          # fi
